### PR TITLE
Rely on 'phly/http' for PSR-7 implementation

### LINKED ISSUE #66: StringStream incompatible with StreamableInterface
`detach` method returns a string, instead of a stream resource.

### PR DESCRIPTION
**Pull request by egeloen**
All is in the title. It fixes #66 and #74 I will probably tweak a little bit the tests but the base code should not change.

Feedback welcome!

### CODE REVIEW

**Comment by jeromegamez** [comment]
So *that's* what you did all the time :). Looks good to me :+1:

**Comment by egeloen** [comment]
@jeromegamez To be honest, I just started to work on this feature 3 days ago. I was busy at work and was a little bit lazy after a workday... :)

**Comment by sagikazarmark** [comment]
Awesome!

**Comment by jeromegamez** [comment]
:+1: <3

**Pull request merged**
