### PR TITLE
Event dispatching improvement

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Solves #84 and #85

**Comment by egeloen** [comment]
I just review the PR and you do an amazing work! Defintively :+1:! Just one missing thing: Can you add a note in the UPGRADE file as it is definitively a big BC break? :)

**Comment by sagikazarmark** [comment]
Sure, added it as 0.7 to 0.8

**Comment by egeloen** [comment]
:+1: Thank you!

**Comment by sagikazarmark** [comment]
Actually this one also closes #85 IMO

**Pull request merged**
