### PR TITLE
Add MockHttpAdapter

### PR DESCRIPTION
**Pull request by tyx**
Allow to stub any HttpAdapter in your test.

We already use it in our test suite, may be it could help anyone else ?

### CODE REVIEW

**Comment by shouze** [comment]
Looks like a :+1:

**Comment by gmorel** [comment]
:+1:

**Comment by egeloen** [comment]
:+1: Can you add some doc?

**Comment by tyx** [comment]
Hi @egeloen !

I just pushed some docs. Let me know if I should do anything else.

**Comment by tyx** [comment]
Hi !

Just see you add the commit into master, great news.

Do you plan to release the 0.8 soon ? The diff starts to be huge : https://github.com/egeloen/ivory-http-adapter/compare/0.7.1...master

Thanks

**Comment by egeloen** [comment]
Thanks for your PR! Your changes have been merged in master via 26d6b7b091326c1d231978de2aa43c7c48d3ed7b

**Pull request closed without merging**
