### PR TITLE
Move event dispatcher into a decorator

### LINKED ISSUE #63: Implement event driven logic as decorator
Currently this logic is encapsulated into all adapters. Implementing it as a decorator would leave it transparent, but make it optional (currently it is not). Also would make the code cleaner. It would probably require some minor structural change in the code.

The point is that decoupling event handling from adapters would make this a plain adapter package, where event layer is an extra on top of it.

What do you think?

### PR DESCRIPTION
**Pull request by egeloen**
This PR fixes #63. Feedbacks welcome!

### CODE REVIEW

**Comment by egeloen** [comment]
ping @sagikazarmark

**Comment by egeloen** [comment]
Btw, I'm not sure if I will leave all the event related code in this repo or if I will create an other one. What do you think?

**Comment by sagikazarmark** [comment]
Seems to be good.

If I were you, I would make the template a trait, as inheritance doesn't really matter here. Would make more sense to use it specifically in the abstract and the decorator.

Actually a separate package would make sense. As soon as the PR is merged (and/or moved to a separate package), I am going to implement an event package using league/event.

**Comment by egeloen** [comment]
You can put abstract method in a trait? Basically, the idea of the template is much more a contract to respect by implementing the `sendInternalRequest` method. This is why I let is as a class.

**Comment by sagikazarmark** [comment]
Yes, you can. Contract or not, inheritance is rather about knowledge than abstraction.

**Comment by egeloen** [comment]
Nice! Not aware we can put an abstract method in a trait but sounds normal. PR updated!

**Comment by sagikazarmark** [comment]
Awesome! :+1:

**Pull request merged**
